### ISSUE TITLE
doc-gen fails for teensy40

### ISSUE THREAD

**Issue by sago35** [tinygo-org/tinygo-site#134]
```
$ go run . teensy40
Generating documentation for: teensy40
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x65bded]

goroutine 1 [running]:
main.writeDoc(0x744ca0, 0xc0000b6078, 0x7ffdc4f22023, 0x8, 0xc0000f60b0, 0xb, 0xb, 0xc000182038, 0x5, 0xc000182051, ...)
        /home/sago35/dev/src/github.com/tinygo-org/tinygo-site/doc-gen/main.go:223 +0xe3d
main.writeTargetDoc(0x7ffdc4f22023, 0x8, 0xc0000b00f0, 0x2f)
        /home/sago35/dev/src/github.com/tinygo-org/tinygo-site/doc-gen/main.go:128 +0x569
main.main()
        /home/sago35/dev/src/github.com/tinygo-org/tinygo-site/doc-gen/main.go:87 +0x249
exit status 2

```

**Comment by sago35** [comment]
crash in the following source code.
https://github.com/tinygo-org/tinygo-site/blob/release/doc-gen/main.go#L223

receiverName is a UART, but doc.Types[UART] does not exist.
docTypes[UARTConfig] does exist.

**Comment by sago35** [comment]
There was a problem in my environment.

The doc-gen is supposed to load %GOPATH%/src/github.com/tinygo-org/tinygo, not the tinygo development directory.
My %GOPATH%/src/github.com/tinygo-org/tinygo was a bit out of date.

I updated %GOPATH%/src/github.com/tinygo-org/tinygo and it worked correctly.
